export const Modules = {
  PROJECTS: "projects",
  PROJECT_TOWERS: "project_towers",
  PROJECT_AMENITIES: "project_amenities",
  PROJECT_MEDIA: "project_media",
  PROPERTY_FEATURES: "property_feature_assignments",
  PROPERTIES: "properties",
  PROPERTY_IMAGES: "property_images",
  PROPERTY_FLOOR_PLANS: "property_floor_plans",
  PROPERTY_BROCHURES: "property_brochures",
  PROPERTY_VIDEOS: "property_videos",
  PROPERTY_PUBLICATIONS: "property_publications",
  PROPERTY_PRICING: "property_pricing_revisions",
  PROPERTY_INVENTORY: "property_inventory_states",
  PROPERTY_INVENTORY_TRANSACTIONS: "property_inventory_transactions",
  PROPERTY_RECOMMENDATIONS: "property_recommendations",
  PROPERTY_COMPARISONS: "property_comparison_sessions",
  USER_FAVORITES: "user_favorites",
  PROPERTY_SHORTLISTS: "property_shortlists",
  DATA_IMPORT_JOBS: "data_import_jobs",
  DATA_IMPORT_ROWS: "data_import_rows",
  DATA_EXPORT_JOBS: "data_export_jobs",
  BUILDERS: "builders",
  LOCATIONS: "locations",
  AMENITIES: "amenities",
  CATEGORIES: "categories",
  CONFIGURATIONS: "configurations",
  LEADS: "leads",
  LEAD_PREFERENCES: "lead_preferences",
  LEAD_ASSIGNMENTS: "lead_assignments",
  LEAD_STATUS: "lead_status_history",
  LEAD_NOTES: "lead_notes",
  LEAD_TIMELINE: "lead_timeline",
  SITE_VISITS: "site_visits",
  CRM_DASHBOARD: "crm_dashboard",
  FOLLOW_UPS: "follow_ups",
  SITE_VISITS: "site_visits",
  CAREERS: "careers",
  USERS: "users",
  NOTIFICATIONS: "notifications",
  ANALYTICS: "analytics",
  AUDIT_LOGS: "audit_logs",
  MEDIA: "media",
  SETTINGS: "settings"
} as const;

export type ModuleName = typeof Modules[keyof typeof Modules];
