export interface PropertyEntity {
  id: string;
  tower_id: string;
  configuration_id: string;
  unit_number: string;
  unit_code: string;
  slug: string;
  floor_number: number | null;
  property_status: 'UNDER_CONSTRUCTION' | 'READY_TO_MOVE' | 'UPCOMING';
  availability_status: 'AVAILABLE' | 'SOLD' | 'ON_HOLD' | 'RESERVED';
  listing_title: string;
  short_description: string | null;
  detailed_description: string | null;
  carpet_area: number | null;
  built_up_area: number | null;
  super_built_up_area: number | null;
  area_unit: string;
  price: number | null;
  maintenance_charge: number | null;
  booking_amount: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  balconies: number | null;
  facing: string | null;
  furnishing_status: string | null;
  ownership_type: string | null;
  parking_slots: number | null;
  is_corner_unit: boolean;
  is_featured: boolean;
  is_verified: boolean;
  is_active: boolean;
  seo_title: string | null;
  seo_description: string | null;
  seo_keywords: string | null;
  canonical_url: string | null;
  display_order: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  created_by: string | null;
  updated_by: string | null;
}
