export interface PropertyFloorPlanEntity {
  id: string;
  property_id: string;
  plan_name: string;
  plan_code: string;
  description: string | null;
  storage_bucket: string;
  storage_path: string;
  public_url: string;
  thumbnail_url: string | null;
  file_format: string;
  drawing_scale: string | null;
  orientation: string | null;
  carpet_area: number | null;
  built_up_area: number | null;
  super_built_up_area: number | null;
  bedrooms: number | null;
  bathrooms: number | null;
  balconies: number | null;
  width: number | null;
  height: number | null;
  file_size: number | null;
  display_order: number;
  is_primary: boolean;
  is_downloadable: boolean;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  created_by: string | null;
  updated_by: string | null;
}
